name: Deploy Tiempo a HostGator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]
  workflow_dispatch:

jobs:
  build-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --no-audit --no-fund
      - name: Build project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci --no-audit --no-fund
        
      - name: Build project
        run: npm run build
        
      - name: Verify build output
        run: |
          echo "Verificando contenido del build..."
          ls -la dist/
          echo "Tamaño total del directorio dist:"
          du -sh dist/
          
      # Verificar credenciales antes del deploy
      - name: Verify FTP credentials
        run: |
          echo "🔐 Verificando configuración FTP..."
          echo "Usuario FTP esperado: tiempo@tiempo.fabrizziodev.com"
          echo "Servidor: ftp.fabrizziodev.com"
          echo "Directorio destino: /home3/fabrizz1/tiempo.fabrizziodev.com/"
          
      # Deploy directo usando servidor HostGator
      - name: Deploy to HostGator via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /
          protocol: sftp
          port: 21
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/src/**
            **/*.map
            **/.env*
            **/test/**
            **/*.test.*
            vite.config.ts
            package*.json
            tsconfig*.json
            README.md
            .gitignore
            eslint.config.js
            vitest.config.ts
            
      - name: Deployment Summary
        if: success()
        run: |
          echo "🚀 Despliegue completado exitosamente"
          echo "📁 Directorio remoto: /home3/fabrizz1/tiempo.fabrizziodev.com/"
          echo "🔗 Commit: ${{ github.sha }}"
          echo "🌐 URL esperada: https://tiempo.fabrizziodev.com"