name: Deploy Tiempo a HostGator

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: deploy-hostgator
  cancel-in-progress: true

jobs:
  deploy:
    name: Build y Deploy a HostGator
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js (con cache de npm)
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci --no-audit --no-fund

      # No se ejecutan pruebas: se omite intencionalmente cualquier paso de "npm test"

      - name: Construir el proyecto
        run: npm run build

      - name: Exportar secretos a variables de entorno
        shell: bash
        run: |
          echo "HOSTGATOR_FTP_SERVER=${{ secrets.HOSTGATOR_FTP_SERVER }}" >> $GITHUB_ENV
          echo "HOSTGATOR_FTP_USERNAME=${{ secrets.HOSTGATOR_FTP_USERNAME }}" >> $GITHUB_ENV
          echo "HOSTGATOR_FTP_PASSWORD=${{ secrets.HOSTGATOR_FTP_PASSWORD }}" >> $GITHUB_ENV
          echo "HOSTGATOR_REMOTE_DIR=${{ secrets.HOSTGATOR_REMOTE_DIR }}" >> $GITHUB_ENV

      - name: Instalar lftp (cliente FTPS)
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Transferir archivos a HostGator (FTPS, mirror -R)
        shell: bash
        run: |
          # Verifica que el build exista
          if [ ! -d "dist" ]; then echo "La carpeta dist no existe"; exit 1; fi

          # Ejecuta lftp con expansión de variables (EOF sin comillas)
          lftp -u "$HOSTGATOR_FTP_USERNAME","$HOSTGATOR_FTP_PASSWORD" "$HOSTGATOR_FTP_SERVER" << EOF
          set net:timeout 45
          set net:max-retries 3
          set net:reconnect-interval-base 5
          set ftp:ssl-allow true
          set ftp:ssl-force true
          set ftp:ssl-protect-data true
          set ftp:passive-mode true
          set cmd:fail-exit true

          # Entra en el dir remoto; si no existe, créalo y entra
          cd "$HOSTGATOR_REMOTE_DIR" || (mkdir -p "$HOSTGATOR_REMOTE_DIR" && cd "$HOSTGATOR_REMOTE_DIR")

          # Asegura el dir local del build
          lcd dist

          # Sube archivos desde dist al directorio remoto actual
          mirror -R \
            --exclude-glob .git* \
            --exclude-glob .github/* \
            --parallel=3 \
            --only-newer \
            --no-perms \
            . .

          bye
          EOF
        env:
          HOSTGATOR_FTP_SERVER: ${{ secrets.HOSTGATOR_FTP_SERVER }}
          HOSTGATOR_FTP_USERNAME: ${{ secrets.HOSTGATOR_FTP_USERNAME }}
          HOSTGATOR_FTP_PASSWORD: ${{ secrets.HOSTGATOR_FTP_PASSWORD }}
          HOSTGATOR_REMOTE_DIR: ${{ secrets.HOSTGATOR_REMOTE_DIR }}